name: Deploy to HubSpot Portal

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: HubSpot Project Upload Action
        env:
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.hubspot_personal_access_key }}
          HUBSPOT_PORTAL_ID: ${{ secrets.hubspot_portal_id }}
        run: npx @hubspot/cli project upload --forceCreate --use-env
        shell: bash



