name: Deploy to HubSpot Portal
description: Deploy to HubSpot Portal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  deployment:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HubSpot Project Upload Action
        env:
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.hubspot_personal_access_key }}
          HUBSPOT_PORTAL_ID: ${{ secrets.hubspot_portal_id }}
        run: npx @hubspot/cli project upload --forceCreate --use-env
        shell: bash



